Repository guilhermelawless/nano-dpow, pull requests merged in 2019-06, with the labels that each got.

#7 replace windows shortcut with a batch file
  client/bin/windows/run_work_server.bat
  client/bin/windows/run_work_server.lnk
Labels: bug

#8 Basic validation for payout arg
  client/config_parse.py
Labels: enhancement

#11 Endpoints in different ports
  server/dpow/config.py
  server/dpow/mqtt.py
  server/dpow_server.py
Labels: enhancement

#16 Resilient websocket with reconnection upon failure or closed session
  server/dpow/nano_websocket.py
  server/dpow_server.py
Labels: enhancement

#17 Add documentation on our MQTT topics and message formats
  README.md
  docs/specification.md
Labels: documentation

#18 Add windows batch file for running client & PoW service
  client/bin/windows/run_work_server.bat
  client/run_windows.bat
Labels: enhancement

#19 Ignore duplicate work requests if in work_ongoing
  client/dpow_client.py
  client/work_handler.py
Labels: bug
